# Generated by Django 3.1.7 on 2021-04-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_auto_20210419_1207'),
        ('mp', '0003_mp_tecnicojefe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.linea'),
        ),
        migrations.AlterField(
            model_name='mp',
            name='tiempoMuerto',
            field=models.CharField(help_text='Tiempo muerto empleado', max_length=5, verbose_name='Tiempo Muerto'),
        ),
    ]
