# Generated by Django 3.1.7 on 2021-03-30 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210329_1357'),
        ('hxh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infogeneral',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.linea'),
        ),
    ]
