# Generated by Django 3.1.7 on 2021-03-30 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hxh', '0002_auto_20210330_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproduccion',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hxh.infogeneral'),
        ),
    ]
