# Generated by Django 3.1.7 on 2021-03-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxh', '0003_auto_20210330_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproduccion',
            name='fecha',
            field=models.DateField(help_text='Fecha', verbose_name='Fecha'),
        ),
    ]
