# Generated by Django 3.1.7 on 2021-07-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxh', '0004_auto_20210330_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='infogeneral',
            name='no_personal',
            field=models.IntegerField(default=0, help_text='Numero de trabajadores en la linea', verbose_name='No. Personal'),
        ),
    ]
