# Generated by Django 3.1.7 on 2021-07-13 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0041_auto_20210713_1828'),
        ('hxh', '0005_infogeneral_no_personal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, default='', help_text='LLave unica de usuario', max_length=32, unique=True, verbose_name='Key')),
                ('name', models.CharField(default='', help_text='Nombre del operador', max_length=255, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, help_text='El usuario sigue laborando?', verbose_name='Trabaja?')),
                ('register', models.DateTimeField(default=datetime.datetime(2021, 7, 13, 18, 28, 8, 653717), help_text='Fecha de inicio laboral', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Miebros de la planta',
                'db_table': 'Staff',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date(2021, 7, 13), help_text='Fecha actual', verbose_name='Dia')),
                ('hora', models.TimeField(help_text='Hora de entrada', verbose_name='Hora')),
                ('linea', models.ForeignKey(help_text='Linea de trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='StaffLineIn', related_query_name='LineOperation', to='usuarios.linea', verbose_name='Linea')),
                ('user', models.ForeignKey(help_text='Usuario correspondiente', on_delete=django.db.models.deletion.PROTECT, related_name='StaffMemberIn', related_query_name='MemberIn', to='hxh.staff', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'db_table': 'Entradas_Staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Loggout',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date(2021, 7, 13), help_text='Fecha actual', verbose_name='Dia')),
                ('hora', models.TimeField(help_text='Hora de entrada', verbose_name='Hora')),
                ('linea', models.ForeignKey(help_text='Linea de trabajo', on_delete=django.db.models.deletion.PROTECT, related_name='StaffLineOff', related_query_name='LineOperationOff', to='usuarios.linea', verbose_name='Linea')),
                ('user', models.ForeignKey(help_text='Usuario correspondiente', on_delete=django.db.models.deletion.PROTECT, related_name='StaffMemberOff', related_query_name='MemberOf', to='hxh.staff', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Salida',
                'verbose_name_plural': 'Salidas',
                'db_table': 'Salidas_Staff',
                'managed': True,
            },
        ),
    ]
