# Generated by Django 3.1.7 on 2021-07-19 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxh', '0006_loggout_signup_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='OFF', help_text='Estatus del trabajador', max_length=5, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='loggout',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 19), help_text='Fecha actual', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 19), help_text='Fecha actual', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='register',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 11, 0, 54, 488474), help_text='Fecha de inicio laboral', verbose_name='Registro'),
        ),
    ]
