# Generated by Django 3.1.7 on 2021-07-19 18:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0044_auto_20210719_1819'),
        ('hxh', '0008_auto_20210719_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='register',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 18, 19, 7, 508283), help_text='Fecha de inicio laboral', verbose_name='Registro'),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='', help_text='Estatus del registro', max_length=5, verbose_name='Estatus')),
                ('registro', models.DateTimeField(default=datetime.datetime(2021, 7, 19, 18, 19, 7, 508283), help_text='Hora del registro', verbose_name='Hora')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='LineResume', related_query_name='ResumeLine', to='usuarios.linea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='UserResume', related_query_name='ResumeUser', to='hxh.staff')),
            ],
            options={
                'verbose_name': 'Hisotrial',
                'verbose_name_plural': 'Records',
                'db_table': 'historial_move',
                'managed': True,
            },
        ),
    ]
