# Generated by Django 3.1.7 on 2021-07-20 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxh', '0009_auto_20210719_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduccion',
            name='operarios',
            field=models.IntegerField(default=0, help_text='Numero de Operarios', verbose_name='Operarios'),
        ),
        migrations.AlterField(
            model_name='history',
            name='registro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 10, 41, 24, 590927), help_text='Hora del registro', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='loggout',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 20), help_text='Fecha actual', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 20), help_text='Fecha actual', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='register',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 20, 10, 41, 24, 590927), help_text='Fecha de inicio laboral', verbose_name='Registro'),
        ),
    ]
