# Generated by Django 3.1.7 on 2021-07-22 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hxh', '0010_auto_20210720_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='registro',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 16, 22, 53, 960186), help_text='Hora del registro', verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='loggout',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 22), help_text='Fecha actual', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='fecha',
            field=models.DateField(default=datetime.date(2021, 7, 22), help_text='Fecha actual', verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='register',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 16, 22, 53, 944513), help_text='Fecha de inicio laboral', verbose_name='Registro'),
        ),
    ]
