# Generated by Django 3.1.7 on 2021-04-01 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0006_auto_20210331_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
                'db_table': 'Maquinas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tarjetas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, default='', help_text='Descripcion de la falla', max_length=1000, verbose_name='Descripcion')),
                ('area', models.CharField(blank=True, default='', help_text='Area encargada', max_length=35, verbose_name='Area')),
                ('categoria', models.CharField(blank=True, default='', help_text='Categoria', max_length=20, verbose_name='Categoria')),
                ('propuesta', models.CharField(blank=True, default='', help_text='Propuesta realizada', max_length=500, verbose_name='Propuesta')),
                ('implementada', models.CharField(blank=True, default='', help_text='Propuesta implementada', max_length=500, verbose_name='PropuestaImplementada')),
                ('tipo', models.BooleanField(help_text='Tarjeta conforme o no', verbose_name='TipoTarjeta')),
                ('fecha', models.DateTimeField(help_text='Fecha y hora de reporte', verbose_name='Fecha')),
                ('localizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.linea')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpm.maquina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'db_table': 'Tarjetas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField(help_text='Dia de la semana', verbose_name='Dia')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpm.maquina')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'db_table': 'Cronograma',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Actividad', max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(help_text='Tipo de Actividad', max_length=50, verbose_name='Tipo')),
                ('status', models.BooleanField(default=None, help_text='OK OR BAD', verbose_name='Status')),
                ('registro', models.DateTimeField(help_text='Hora de reporte', verbose_name='Registro')),
                ('maquinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpm.maquina')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
                'db_table': 'Actividades',
                'managed': True,
            },
        ),
    ]
