# Generated by Django 3.1.7 on 2021-04-08 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tpm', '0002_auto_20210408_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='sel_com',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('com', models.CharField(blank=True, default='', help_text='Puerto COM', max_length=10, verbose_name='COM')),
            ],
            options={
                'verbose_name': 'selCom',
                'verbose_name_plural': 'selComs',
                'db_table': 'sel_com',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='com',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userCom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='com',
            table='comhist',
        ),
        migrations.AlterField(
            model_name='com',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selCom', to='tpm.sel_com'),
        ),
    ]
