# Generated by Django 3.1.7 on 2021-03-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='andon',
            table='Andon',
        ),
    ]
