# Generated by Django 3.1.7 on 2021-03-31 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210329_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andon',
            name='linea',
        ),
        migrations.AddField(
            model_name='andon',
            name='linea',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Estados', to='usuarios.linea'),
        ),
    ]
