# Generated by Django 3.1.7 on 2021-03-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_andonhist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andonhist',
            name='estatus',
            field=models.CharField(help_text='Estado de la linea en ese momento', max_length=15, verbose_name='Estatus'),
        ),
    ]
