# Generated by Django 3.1.7 on 2021-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210331_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andonhist',
            name='registro',
            field=models.DateTimeField(verbose_name='Fecha de reporte'),
        ),
    ]
