# Generated by Django 3.1.7 on 2021-04-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20210331_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='andon',
            name='registro',
            field=models.DateTimeField(default=None, help_text='Inicio del andon', verbose_name='Registro'),
        ),
    ]
