# Generated by Django 3.1.7 on 2021-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_andon_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='andon',
            name='active',
            field=models.BooleanField(default=True, help_text='Esta pausado?', verbose_name='Active'),
        ),
    ]
