# Generated by Django 3.1.7 on 2021-04-05 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_andon_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linAndon', to='usuarios.linea'),
        ),
    ]
