# Generated by Django 3.1.7 on 2021-04-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_auto_20210405_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(default='Chelsea Sanchez', max_length=50, unique=True),
        ),
    ]
