# Generated by Django 3.1.7 on 2021-04-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_auto_20210405_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='clave',
        ),
    ]
