# Generated by Django 3.1.7 on 2021-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_remove_usuarios_clave'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='clave',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
