# Generated by Django 3.1.7 on 2021-04-05 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_usuarios_clave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='clave',
        ),
    ]
