# Generated by Django 3.1.7 on 2021-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_andon_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='pause',
            field=models.DateTimeField(default=None, help_text='Hora de pausa', verbose_name='Pause'),
        ),
    ]
