# Generated by Django 3.1.7 on 2021-04-05 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0020_auto_20210405_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='active',
            field=models.BooleanField(default=datetime.datetime(2021, 4, 5, 16, 21, 36, 570424), help_text='Esta pausado?', verbose_name='Active'),
        ),
    ]
