# Generated by Django 3.1.7 on 2021-04-05 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0021_auto_20210405_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='active',
            field=models.BooleanField(help_text='Esta pausado?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='andon',
            name='pause',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 16, 22, 18, 275684), help_text='Hora de pausa', verbose_name='Pause'),
        ),
    ]
