# Generated by Django 3.1.7 on 2021-04-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20210405_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='pause',
            field=models.DateTimeField(help_text='Hora de pausa', verbose_name='Pause'),
        ),
    ]
