# Generated by Django 3.1.7 on 2021-04-05 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0023_auto_20210405_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andon',
            name='pause',
        ),
    ]
