# Generated by Django 3.1.7 on 2021-04-05 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0028_auto_20210405_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andon',
            old_name='pause',
            new_name='stop',
        ),
    ]
