# Generated by Django 3.1.7 on 2021-04-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0029_auto_20210405_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='stop',
            field=models.DateTimeField(help_text='Hora de pausa', verbose_name='Pause'),
        ),
    ]
