# Generated by Django 3.1.7 on 2021-04-05 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0031_remove_andon_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='andon',
            name='pause',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 16, 38, 35, 467737), help_text='Hora de pausa', verbose_name='Pause'),
        ),
    ]
