# Generated by Django 3.1.7 on 2021-04-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0032_andon_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andon',
            name='active',
            field=models.BooleanField(default=True, help_text='Esta pausado?', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='andon',
            name='pause',
            field=models.CharField(blank=True, default='', help_text='Hora de pausa', max_length=1500, verbose_name='Pause'),
        ),
    ]
