# Generated by Django 3.1.7 on 2021-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0033_auto_20210406_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='user_type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='linea',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
