# Generated by Django 3.1.7 on 2021-04-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0034_auto_20210409_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', related_query_name='production', to=settings.AUTH_USER_MODEL),
        ),
    ]
