# Generated by Django 3.1.7 on 2021-06-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0035_auto_20210419_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='andonhist',
            name='razon',
            field=models.CharField(default='', help_text='Razon de la falla', max_length=50, verbose_name='Razon de la falla'),
        ),
        migrations.AddField(
            model_name='andonhist',
            name='tiempoM',
            field=models.CharField(blank=True, default='', help_text='Tiempo Muerto', max_length=50, verbose_name='Tiempo Muerto'),
        ),
    ]
