# Generated by Django 3.1.7 on 2021-07-02 09:45

from datetime import datetime
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0037_usuarios_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='andonhist',
            old_name='razon',
            new_name='finishDep',
        ),
        migrations.AddField(
            model_name='andonhist',
            name='finishReg',
            field=models.DateTimeField(default=datetime.now(), help_text='Fecha y hora exacta de finalizacion', verbose_name='Fin Tiempo Muerto'),
        ),
        migrations.AlterField(
            model_name='andonhist',
            name='estatus',
            field=models.CharField(help_text='Estado inicial de la linea en ese momento', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='andonhist',
            name='registro',
            field=models.DateTimeField(verbose_name='Fecha y hora de reporte'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='dep',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
