# Generated by Django 3.1.7 on 2021-07-12 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0038_auto_20210702_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='personal',
            field=models.IntegerField(default=0, help_text='Numero de personal en la linea', verbose_name='Personal'),
        ),
        migrations.AlterField(
            model_name='andonhist',
            name='finishReg',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 12, 12, 5, 16, 874364), help_text='Fecha y hora exacta de finalizacion', verbose_name='Fin Tiempo Muerto'),
        ),
    ]
