# Generated by Django 3.1.7 on 2021-07-13 10:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0039_auto_20210712_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andonhist',
            name='finishReg',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 13, 10, 31, 16, 10753), help_text='Fecha y hora exacta de finalizacion', verbose_name='Fin Tiempo Muerto'),
        ),
        migrations.CreateModel(
            name='LineaStaff',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('turno', models.CharField(default='', help_text='Turno de produccion', max_length=20, verbose_name='Turno')),
                ('staff', models.IntegerField(default=0, help_text='Número de trabajadores en el turno', verbose_name='Trabajadores')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', related_query_name='LineStaff', to='usuarios.linea')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Lines Staff',
                'db_table': 'LineaStaff',
                'managed': True,
            },
        ),
    ]
