# Generated by Django 3.1.7 on 2021-07-19 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0043_auto_20210719_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='andonhist',
            name='finishReg',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 19, 18, 19, 7, 496027), help_text='Fecha y hora exacta de finalizacion', verbose_name='Fin Tiempo Muerto'),
        ),
    ]
